name: Ejemplo de Composición

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2

      - name: Instalar Dependencias
        run: npm install

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2

      - name: Instalar Dependencias
        run: npm install

      - name: Lint con ESLint
        run: npx eslint 'javascript/**/*.js' --fix

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2

      - name: Instalar Dependencias
        run: npm install | npm install --save-dev jest@latest | npm install --save-dev jest | npm install yargs@latest | npm install jest@latest

      - name: Ejecutar Pruebas
        run: npm audit | npm audit fix

  compose:
    needs: [build, lint, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2

      - name: Despliegue de Composición
        run: echo "Composición completada"
