name: javascript
run-name: Accion de javascript
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout    
        id: checkout    
        uses: actions/checkout@v4
      - name: Run my Action    
        id: run-action    
        uses: actions/javascript-action@v1 # Commit with the `v1` tag    
        with:
          milliseconds: 1000
      - name: Print Output    
        id: output
        run: echo "hola"
      - name: Debug
        run: |
          pwd
          ls -l javascript/tests/sum.test.js
      - name: Ensure execute permission on test file
        run: chmod +x javascript/tests/sum.test.js
      - name: test    
        id: test
        run: ../../javascript/test/sum.test.js
